var students = [{"name":"Delly Blabey","age":25,"course":"Andalax"},
{"name":"Rodolphe Furniss","age":23,"course":"Wrapsafe"},
{"name":"Augusta Pelman","age":30,"course":"Overhold"},
{"name":"Rafaello Troak","age":24,"course":"Voyatouch"},
{"name":"Bret Belk","age":25,"course":"Temp"},
{"name":"Chere Aupol","age":20,"course":"Vagram"},
{"name":"Maximilien Dudney","age":23,"course":"Lotstring"},
{"name":"Giusto Orknay","age":28,"course":"Biodex"},
{"name":"Aura Lodemann","age":29,"course":"Viva"},
{"name":"Agace Griffin","age":22,"course":"Span"},
{"name":"Care Charlwood","age":27,"course":"Ronstring"},
{"name":"Tessie O'Shavlan","age":22,"course":"Y-Solowarm"},
{"name":"Kort Izat","age":20,"course":"Voyatouch"},
{"name":"Riane Gutherson","age":20,"course":"Fix San"},
{"name":"Demetri East","age":19,"course":"Treeflex"},
{"name":"Dana Strover","age":30,"course":"Voltsillam"},
{"name":"Kaela McGeady","age":26,"course":"Otcom"},
{"name":"Keenan Baglow","age":21,"course":"Stringtough"},
{"name":"Abram Cadore","age":21,"course":"Prodder"},
{"name":"Estrella Faulkes","age":20,"course":"Flexidy"},
{"name":"Alfy Silly","age":23,"course":"Andalax"},
{"name":"Norean Povele","age":27,"course":"Asoka"},
{"name":"Hestia McSperron","age":28,"course":"Zoolab"},
{"name":"Derron Ellerman","age":29,"course":"Cardify"},
{"name":"Evangeline O'Fogarty","age":21,"course":"Viva"},
{"name":"Tawsha Hegg","age":29,"course":"Rank"},
{"name":"John Learned","age":21,"course":"Y-find"},
{"name":"Antony Summerlad","age":23,"course":"Daltfresh"},
{"name":"Padriac Buckel","age":28,"course":"Redhold"},
{"name":"Madelina Danes","age":20,"course":"Stringtough"},
{"name":"Aleece Muzzlewhite","age":18,"course":"Toughjoyfax"},
{"name":"Martina Merigot","age":30,"course":"Gembucket"},
{"name":"Darius Lambirth","age":20,"course":"Bamity"},
{"name":"Isabeau Papa","age":27,"course":"Otcom"},
{"name":"Petunia Wykes","age":21,"course":"Subin"},
{"name":"Shawn Pargent","age":25,"course":"Flowdesk"},
{"name":"Georgie Alvar","age":18,"course":"Alphazap"}];


export default students;